# -*- coding: utf-8 -*-
"""Scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMpT8h1JnHLdyuUolTex5ZGnJTKGx6px
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/adult.csv')

df.head()

print("Initial Shape:", df.shape)

df.columns = df.columns.str.strip()

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

df.replace("?", np.nan, inplace=True)

print("Missing Values Before Handling:\n", df.isna().sum())

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="most_frequent")
df[df.select_dtypes(include="object").columns] = imputer.fit_transform(df[df.select_dtypes(include="object").columns])

numerical_features = [
    "age",
    "fnlwgt",
    "education.num",
    "capital.gain",
    "capital.loss",
    "hours.per.week"
]

categorical_features = [
    "workclass",
    "marital.status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native.country"
]

target = "income"

X = df.drop(columns=target)
y = df[target]

from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

plt.figure(figsize=(5,4))
sns.countplot(x=df[target])
plt.title("Income Distribution")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df[numerical_features].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap (Numerical Features)")
plt.show()

from sklearn.pipeline import Pipeline

num_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])

from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(transformers=[
    ("num", num_pipeline, numerical_features),
    ("cat", cat_pipeline, categorical_features)
])

X_processed = preprocessor.fit_transform(X)

encoded_cat_features = (
    preprocessor.named_transformers_["cat"]
    .named_steps["onehot"]
    .get_feature_names_out(categorical_features)
)

final_feature_names = np.concatenate([
    numerical_features,
    encoded_cat_features
])

X_processed_df = pd.DataFrame(
    X_processed,
    columns=final_feature_names
)

final_df = pd.concat(
    [X_processed_df, pd.Series(y, name=target)],
    axis=1
)

print("\nFinal Dataset Shape:", final_df.shape)

final_df.to_csv("adult_processed_sklearn.csv", index=False)

print("\nFeature Encoding, Scaling & Missing Value Handling Completed")
print("Saved as: adult_processed_sklearn.csv")

